---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
    #login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #check out the code for actual actions
      - name: Checkout
        uses: actions/checkout@v2
      
      #run unit test
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      #run linting
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

